title: Manage Your Money Like a Fucking Grownup
url: likeafuckinggrownup.com
locale: "en-GB"
email: howzit@likeafuckinggrownup.com
name: "Sam Beckbessinger"
excerpt_separator: <!--more-->
description: > # this means to ignore newlines until "baseurl:"
  A community learning to be grownups about managing our money. Come say hi, learn some stuff.
twitter_username: "beckbessinger"
github_username:  "greenhamsam"
repository: "greenhamsam/fresh-jekyll"
future: true
permalink: /:categories/:title.html

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

author:
  name   : "Sam Beckbessinger"
  bio    : "Money dork. Entrepreneur."
  email  : "howzit@fuckinggrownups.com"

# # Comments
#  comments:
#    provider: disqus
#  disqus:
#    short_name: like-a-fucking-grownup

# Build settings
# markdown: redcarpet
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
